### ISSUE TITLE
Playlist section contains different image thumbnail sizes

### ISSUE THREAD

**Issue by aforloney** [iansantagata/jamms#26]
## The Problem
When viewing my playlists, I am seeing various size thumbnails for the playlist image.

## Expected Behavior
As an end-user, I expect a consistent image size to be respected for all playlist thumbnails.

## Steps to Reproduce the Problem

1. Log onto the application with your Spotify credentials
2. From the home screen, navigate to the Playlists section
3. Scroll down and notice various image sizes for Playlist thumbnails

## Additional Information
N/A

### Screenshots
Attached
![image](https://user-images.githubusercontent.com/3209784/136675100-6a609595-2f0b-439f-b0fb-bc33c2012ecc.png)

### Platform
Device: macOS Big Sur 11.6
Browser: Google Chrome Version 94.0.4606.61 (Official Build) (x86_64)

**Comment by iansantagata** [comment]
Thanks for the report here, @aforloney!  

Fixed this bug for you in this PR that I just merged - https://github.com/iansantagata/jamms/pull/96

Let me know if you see anything still amiss!
